### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by lauhasd** [jacobstanley/elm-font-awesome#13]
We're getting error when installing this package:
```bash
$ elm-package install jystic/elm-font-awesome
To install jystic/elm-font-awesome I would like to add the following
dependency to elm-package.json:

    "jystic/elm-font-awesome": "3.0.0 <= v < 4.0.0"

May I add that to elm-package.json for you? [Y/n] 

Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/svg 2.0.0
    jystic/elm-font-awesome 3.0.0

Do you approve of this plan? [Y/n] 
Starting downloads...

  ● elm-lang/svg 2.0.0
  ✗ jystic/elm-font-awesome 3.0.0
Error: Problem when downloading the jystic/elm-font-awesome 3.0.0 code.
```
We're using elm 0.18

Could this be caused by a change in the Github repository url (see 
 [elm-package.json](https://github.com/jacobstanley/elm-font-awesome/blob/master/elm-package.json#L4))?

**Comment by jacobstanley** [comment]
> Could this be caused by a change in the Github repository url (see elm-package.json)?

That certainly looks suspicious. So I renamed my github account from `jystic` to `jacobstanley`, but I'm not sure why it isn't working as if I do:

```
git clone https://github.com/jystic/elm-font-awesome
```

Then github redirects us here and everything works! Let me try updating the `elm-package.json` and see if you have more luck.

**Comment by jacobstanley** [comment]
I couldn't see how to install elm-0.18 easily (so I could use `elm bump`, etc on an `elm-package.json` file) so I've just done it manually.

Maybe try now with v3.0.1 at https://github.com/jacobstanley/elm-font-awesome ?

Hmm although, it might not work as I haven't done `elm publish`, I'll try to build elm-0.18 from source.

**Comment by jacobstanley** [comment]
OK, so `elm-publish` didn't like publishing a new version starting from `3.0.1`, so I have recreated @jystic and forked this [elm-font-awesome](https://github.com/jacobstanley/elm-font-awesome) to [there](https://github.com/jystic/elm-font-awesome). Hopefully that fixes it, maybe try again?

**Comment by lauhasd** [comment]
Great, `elm-package` is able to install it correctly now that `github.com/jystic/elm-font-awesome` exists.
Thanks for the quick response! :)

**Comment by jacobstanley** [comment]
Yay :relieved: happy to help
